### ISSUE TITLE
Spartanizer is back (but there are two classes)

### ISSUE THREAD

**Issue by M4tt30rru** [SpartanRefactoring/Spartanizer#435]
Spartanizer is working again. However, there are two spartanizer classes in this very moment: one with the capital letter (Spartanizer) and one without (spartanizer). The second one is not working, as far as I know. I was certainly working on the first version before your push. 
@yossigil If you did not make changes after our meeting today I can delete the second one and rename the first as "spartanizer".

**Comment by yossigil** [comment]
Go ahead. I think it is DOS related.

**Comment by yossigil** [comment]
Done?

**Comment by M4tt30rru** [comment]
Not yet. I managed to remove @Test annotated methods on the tests. But it is still not working on the spartanizer. I am still working on it.

**Comment by yossigil** [comment]
Should this still be open?
